runtime: go116
instance_class: F1

default_expiration: '1d'

automatic_scaling:
  max_concurrent_requests: 64
  max_idle_instances: automatic

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env_variables:
  ENVIRONMENT: 'master'
  DIST_FOLDER: 'dist'
  OMDB_KEY: '3e5351f0'
  CLOUD_STORAGE_BUCKET: 'watchlist-lost-marbles.appspot.com'
  GAE_DATASTORE_HOST: 'watchlist-lost-marbles.appspot.com'
